### ISSUE TITLE
Support format variants for long file names

### ISSUE THREAD

**Issue by mdsteele** [mdsteele/rust-ar#1]
The "common" ar format only supports filenames up to 16 characters.  Apparently there are [two common variants](https://en.wikipedia.org/wiki/Ar_(Unix)#File_header) for supporting longer file names.  Probably the library should support reading/writing at least one of those, and ideally both.

**Comment by mdsteele** [comment]
As of 8712dc8, this library now supports reading/writing BSD-variant archive files (in addition to the "common" variant, which is a subset of the BSD variant), but still doesn't support reading or writing GNU-variant archive files.

**Comment by aep** [comment]
@mdsteele  is that still the case? the docs actually say it supports GNU archives

**Comment by mdsteele** [comment]
Thanks, yes, this bug is out of date -- the latest version of the library supports reading (some) GNU archives.  Except whoops, you're right, it is not working on the file you linked to.

After a few minutes of poking, looks like the problem is that the current version of the library is not handling the [symbol lookup table](https://en.wikipedia.org/wiki/Ar_(Unix)#System_V_.28or_GNU.29_variant) entry in that archive.  Also, the error message it returns isn't particularly helpful.

I'll look into fixing both of these issues.

**Comment by mdsteele** [comment]
Thanks again for the report.  I've just published [v0.3.1](https://crates.io/crates/ar/0.3.1) to fix this problem.  I am now able to read the archive file you linked to with the library.  Also, some of the error messages have been (slightly) improved.

**Comment by aep** [comment]
works for me. thanks!
