### ISSUE TITLE
0.7 is released but the changes are not on github?

### ISSUE THREAD

**Issue by Marwes** [mdsteele/rust-ar#12]
https://github.com/mdsteele/rust-ar/blob/master/Cargo.toml says the version is 0.6.2 but a 0.7 seems to be released https://crates.io/crates/ar?

**Comment by bjorn3** [comment]
It seems the version bump commit hasnt been pushed to master, but there is an `v0.7.0` tag.

**Comment by mdsteele** [comment]
Whoops, fixed.
