### ISSUE TITLE
Windows `.lib` files do not use UTF-16.

### ISSUE THREAD

**Issue by eddyb** [mdsteele/rust-ar#19]
In d68690d0aff194db4959763d1cb707984fd6a36b, an `OsStr -> UTF-16` encoding step was added on Windows, but neither Rust `.rlib`s nor MSVC `.lib`s appear to use that format.

IME, the names of object files in an archive also tend to be ASCII, so a simple solution would be to revert d68690d0aff194db4959763d1cb707984fd6a36b - however, I haven't checked what MSVC does if you do have unicode in a file name.

I may PR a change here but I first want to make sure I understand what the full spectrum of behaviors is.

**Comment by eddyb** [comment]
Just confirmed (using a file name with some Cyrillic in it) that `LIB.EXE` includes the UTF-8 encoding of a `.obj` file name, so `osstr_to_bytes` should just have a single `cfg(not(unix))` case, only allowing non-UTF-8 on UNIX.

**Comment by bjorn3** [comment]
What happens when you use an unpaired surrogate in the filename? Does msvc give an error? Or does it use something like WTF-8 to encode it?

**Comment by eddyb** [comment]
I've done the unpaired surrogate test using [a small Rust program to drive everything](https://gist.github.com/eddyb/a88d71555ece9f8761fa8844a331e950).
The actual compiler doesn't seem to allow invalid UTF-8 in filenames, so I had to rename the input file.
`LIB.EXE` doesn't give an error, but it does encode `U+FFFD` in UTF-8 (`\xEF\xBF\xBD`), instead of my surrogate.

So we could use `to_str_lossy()` if we wanted to mimic that, but an error seems saner than corrupting the input.
