### ISSUE TITLE
Seek for ar::Entry

### ISSUE THREAD

**Issue by aep** [mdsteele/rust-ar#2]
it would be very convenient to get Seek on ar::Entry,
otherwise i have to copy it into an intermediate buffer, making it less efficient.

thinking of an alternative  Entry::into_reader which consumes entry and returns the internal io i've figured the internal io is actually Take which doesnt have Seek, so maybe the best action would be some lower level api that adds offset to the Header instead and let's the user operate on the original io instead.

**Comment by mdsteele** [comment]
Good idea.  Fixed in d5695a6 -- `Entry` now supports `Seek` if the underlying reader supports `Seek`.

**Comment by aep** [comment]
nice! thanks alot.

unfortunately it wont help in my case since Entry has the Read by_ref rather than cloned.
I can't really process those independently of each other across threads.

https://github.com/aep/elfkit/blob/refactor/bin/findsym.rs#L116

What do you think about having an Entry::offset() ?
I could just call Seek(Current(0)) on io to get the offset, but that would rely on rust-ar never changing the by_ref
